#!/usr/bin/env bash
case $1 in

  init)
    docker run -d \
      --shm-size=4g \
      -p 127.0.0.1:5902:6080 \
      --cap-add=SYS_PTRACE \
      --security-opt seccomp=unconfined \
      --security-opt=apparmor:unconfined \
      --name plwitico-melodic \
      ssilenzi/plwitico:melodic-local
    docker cp "$(dirname ""$0"")/smartgit" plwitico-melodic:/home/ubuntu/.config/
    docker exec -it plwitico-melodic bash -c "sudo chown -R ubuntu:ubuntu /home/ubuntu/.config/smartgit/"
    docker cp "$(dirname ""$0"")/melodic-init.sh" plwitico-melodic:/workspace/
    docker exec -it plwitico-melodic bash -i -c "sudo chown ubuntu:ubuntu /workspace/melodic-init.sh; \
                                      bash /workspace/melodic-init.sh; \
                                      rm /workspace/melodic-init.sh"
    exit $?
    ;;
  
  rm)
    docker rm -v -f plwitico-melodic
    exit $?
    ;;
    
  shell)
    docker exec -it -w /workspace/planning-with-tight-constraints plwitico-melodic bash -i
    exit $?
    ;;
  
  start)
    docker start plwitico-melodic
    exit $?
    ;;
  
  stop)
    docker stop plwitico-melodic
    exit $?
    ;;

  *)
    echo "No start / stop supplied"
    exit 1
    ;;

esac
